# -*- coding: utf-8 -*-
"""E_Commerce_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6ArOGMBdEJtzBzQQWKhX398K2rowBsL

# E-Commerce Sales Analysis Using Python and Power BI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

import zipfile

with zipfile.ZipFile("archive (11).zip", "r") as zip_ref:
    zip_ref.extractall("/content")

import os

print(os.listdir("/content"))

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
translation = pd.read_csv("product_category_name_translation.csv")

orders

"""# Understanding the data"""

# shape of data
print("orders",orders.shape)
print("order Items:",order_items.shape)
print("products:",products.shape)
print("customers",customers.shape)
print("Reviews:",reviews.shape)
print("Transalation",translation.shape)

# viewing initial data
orders.head()
order_items.head()
products.head()
customers.head()
reviews.head()
translation.head()

# check the columns
orders.columns

# check datatype
orders.info()

orders.info()
order_items.info()
products.info()
customers.info()
reviews.info()
translation.info()

# checking missing values
orders.isnull().sum()

# checking duplicated sum
orders.duplicated().sum()

# statistical summary
order_items.describe()

"""# Data Cleaning"""

# Check Missing Values
print("Orders")
print(orders.isnull().sum())

print("\nOrder Items")
print(order_items.isnull().sum())

print("\nProducts")
print(products.isnull().sum())

print("\nCustomers")
print(customers.isnull().sum())

print("\nReviews")
print(reviews.isnull().sum())

print("\nTranslation")
print(translation.isnull().sum())

# Remove Duplicate Records
orders.drop_duplicates(inplace=True)
order_items.drop_duplicates(inplace=True)
products.drop_duplicates(inplace=True)
customers.drop_duplicates(inplace=True)
reviews.drop_duplicates(inplace=True)
translation.drop_duplicates(inplace=True)

# Convert Date Columns
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

# Merge Product Category Translation
products = products.merge(
    translation,
    on="product_category_name",
    how="left"
)

# Merge All Datasets

# Merge Orders + Customers
df = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

# Merge Order Items
df = df.merge(
    order_items,
    on="order_id",
    how="left"
)

# Merge Products
df = df.merge(
    products,
    on="product_id",
    how="left"
)

# Merge Reviews
df = df.merge(
    reviews,
    on="order_id",
    how="left"
)

# 4.6 Check the Final Dataset
df.head()

# Feature Engineering

# Month
df["Month"] = df["order_purchase_timestamp"].dt.month_name()

# Year
df["Year"] = df["order_purchase_timestamp"].dt.year

"""## Data Cleaning Summary"""

### Data Cleaning Summary

The following data cleaning steps were performed before analysis:

| Cleaning Step | Action Taken |
|---------------|--------------|
| Missing Values | Checked missing values in all datasets using `isnull().sum()`. Missing values were found mainly in product and review-related columns. No missing values in key columns (`order_id`, `customer_id`, `product_id`) required removal. |
| Duplicate Records | Checked for duplicate records using `duplicated().sum()` and removed them using `drop_duplicates()`. |
| Data Types | Converted all order date columns from object type to datetime using `pd.to_datetime()`. |
| Category Translation | Merged the product category translation table to obtain English category names. |
| Data Integration | Merged the orders, customers, order items, products, and reviews datasets into a single DataFrame for analysis. |

"""# Exploratory Data Analysis (EDA)"""

# Which product category has the highest revenue?
category_revenue = (
    df.groupby("product_category_name_english")["price"]
      .sum()
      .sort_values(ascending=False)
)

category_revenue.head(10)

# Which month had peak sales?

# Step 1: Create Month Column (if not already created)
df["Month"] = df["order_purchase_timestamp"].dt.month_name()

# Step 2: Arrange months correctly
month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

monthly_sales = (
    df.groupby("Month")["price"]
      .sum()
      .reindex(month_order)
)

monthly_sales

# Which region performs best?

state_sales = (
    df.groupby("customer_state")["price"]
      .sum()
      .sort_values(ascending=False)
)

state_sales.head(10)

# What is the average order value trend?

# Step 1: Calculate total value of each order
order_value = (
    df.groupby("order_id")
    .agg(
        order_value=("price", "sum"),
        purchase_date=("order_purchase_timestamp", "first")
    )
    .reset_index()
)
# Step 2: Extract month
order_value["Month"] = order_value["purchase_date"].dt.month_name()

# Step 3: Calculate average order value
avg_order = (
    order_value.groupby("Month")["order_value"]
               .mean()
               .reindex(month_order)
)

avg_order

# What is the customer review score distribution?

review_distribution = (
    df["review_score"]
      .value_counts()
      .sort_index()
)

review_distribution

"""# Create Visualizations"""

# Load category translation dataset

category = pd.read_csv(
    '/content/product_category_name_translation.csv'
)

category.head()

merged_df = order_items.merge(
    products,
    on='product_id',
    how='left'
)

merged_df = merged_df.merge(
    category,
    on='product_category_name',
    how='left'
)

merged_df = merged_df.merge(
    orders,
    on='order_id',
    how='left'
)

merged_df = merged_df.merge(
    customers,
    on='customer_id',
    how='left'
)

merged_df = merged_df.merge(
    reviews,
    on='order_id',
    how='left'
)

print(merged_df.shape)
merged_df.head()

print(merged_df.columns)

print(merged_df.columns.tolist())

# Revenue by category

revenue = merged_df.groupby(
    'product_category_name_english_x'
)['price'].sum().sort_values(
    ascending=False
)

print(revenue.head(10))
plt.figure(figsize=(12,6))

revenue.head(10).plot(
    kind='bar'
)

plt.title('Top 10 Product Categories by Revenue')

plt.xlabel('Product Category')

plt.ylabel('Revenue')

plt.xticks(rotation=45)

plt.show()

# 2. Monthly Sales Trend

# 2. Monthly Sales Trend

# Extract month from order date
merged_df['Month'] = merged_df[
    'order_purchase_timestamp'
].dt.month_name()

# Arrange months in correct order
month_order = [
    'January','February','March',
    'April','May','June',
    'July','August','September',
    'October','November','December'
]

monthly_sales = merged_df.groupby(
    'Month'
)['price'].sum().reindex(
    month_order
)

print(monthly_sales)
plt.figure(figsize=(12,6))

plt.plot(
    monthly_sales.index,
    monthly_sales.values,
    marker='o'
)

plt.title(
    'Monthly Sales Trend'
)

plt.xlabel(
    'Month'
)

plt.ylabel(
    'Total Sales'
)

plt.xticks(rotation=45)

plt.grid()

plt.show()

# 3. Regional Sales

# Bar Chart
# 3. Regional Sales

regional_sales = merged_df.groupby(
    'customer_state'
)['price'].sum().sort_values(
    ascending=False
)

print(regional_sales.head(10))
plt.figure(figsize=(12,6))

regional_sales.head(10).plot(
    kind='bar'
)

plt.title(
    'Top 10 Regions by Sales'
)

plt.xlabel(
    'State'
)

plt.ylabel(
    'Total Revenue'
)

plt.xticks(rotation=45)

plt.show()

# 4. Order Value Distribution
# Histogram

# Calculate total order value

order_values = merged_df.groupby(
    'order_id'
)['price'].sum()

plt.figure(figsize=(12,6))

plt.hist(
    order_values,
    bins=30
)

plt.title(
    'Order Value Distribution'
)

plt.xlabel(
    'Order Value'
)

plt.ylabel(
    'Frequency'
)

plt.show()

# 5. Review Score Distribution

# Pie Chart
# 5. Review Score Distribution

review_scores = merged_df[
    'review_score'
].value_counts().sort_index()

print(review_scores)

plt.figure(figsize=(8,8))

plt.pie(
    review_scores,
    labels=review_scores.index,
    autopct='%1.1f%%'
)

plt.title(
    'Customer Review Score Distribution'
)

plt.show()

# 6. Category vs Month
# Heatmap
# 6. Category vs Month Heatmap

heatmap_data = merged_df.pivot_table(
    values='price',
    index='product_category_name_english_x',
    columns='Month',
    aggfunc='sum'
)
plt.figure(figsize=(14,8))

sns.heatmap(
    heatmap_data,
    cmap='YlGnBu'
)

plt.title(
    'Category vs Month Sales Heatmap'
)

plt.xlabel(
    'Month'
)

plt.ylabel(
    'Product Category'
)

plt.show()



# ==========================
# Dashboard KPIs
# ==========================

total_revenue = merged_df['price'].sum()

total_orders = merged_df[
    'order_id'
].nunique()

top_category = revenue.idxmax()

best_month = monthly_sales.idxmax()

"""#  Dashboard"""

# ==========================
# Dashboard
# ==========================

fig = plt.figure(figsize=(18,10))

# KPI Cards
fig.text(
    0.05,
    0.92,
    f"Total Revenue\n₹{round(total_revenue,2)}",
    fontsize=14
)

fig.text(
    0.30,
    0.92,
    f"Total Orders\n{total_orders}",
    fontsize=14
)

fig.text(
    0.55,
    0.92,
    f"Top Category\n{top_category}",
    fontsize=14
)

fig.text(
    0.80,
    0.92,
    f"Best Month\n{best_month}",
    fontsize=14
)

# Revenue Chart
plt.subplot(2,2,1)
revenue.head(5).plot(kind='bar')
plt.title("Top Revenue Categories")
plt.xticks(rotation=45)

# Monthly Trend
plt.subplot(2,2,2)
monthly_sales.plot(marker='o')
plt.title("Monthly Sales Trend")
plt.xticks(rotation=45)

# Regional Sales
plt.subplot(2,2,3)
regional_sales.head(5).plot(kind='bar')
plt.title("Regional Sales")
plt.xticks(rotation=45)

# Review Scores
plt.subplot(2,2,4)
review_scores.plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.ylabel("")
plt.title("Review Distribution")

plt.tight_layout()

plt.show()



"""# Business Insights Report"""

# Business Insights Report

# Insight 1
Finding: Revenue by category analysis shows that [your top category] generated the highest revenue. This indicates strong customer demand for this category.

Recommendation: Increase stock availability and run targeted advertisements for this category.

# Insight 2
Finding: Monthly trend analysis shows that [your best month] recorded peak sales.

Recommendation: Launch campaigns and discount offers before this period.

# Insight 3
Finding: Regional sales analysis shows that [your top state/region] contributed the highest revenue.

Recommendation: Expand marketing efforts and customer engagement in this region.

# Insight 4
Finding: Order value distribution indicates that most orders fall within a specific range, while high-value purchases are less frequent.

Recommendation: Introduce bundle offers and upselling strategies.

# Insight 5
Finding: Review score distribution shows that most customers gave positive ratings.

Recommendation: Analyze low-rated reviews and improve customer experience.